../../lem-in -e < 1
../../lem-in -e < 2
../../lem-in -e < 3
../../lem-in -e < 4
../../lem-in -e < 5
../../lem-in -e < 6
../../lem-in -e < 7
../../lem-in -e < 8
../../lem-in -e < 9
../../lem-in -e < 10
../../lem-in -e < 11
../../lem-in -e < 12
../../lem-in -e < 13
../../lem-in -e < 14
../../lem-in -e < 15
../../lem-in -e < 16
../../lem-in -e < 17
../../lem-in -e < 18
../../lem-in -e < 148
echo
../../lem-in -e < 19
